{
 "title": "Ops - Cluster Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": "label_values(kube_pod_info,cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\",cluster=~\"$Cluster\"} == 1))"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "datasource" },
  {
   "title": "API Up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\",cluster=~\"$Cluster\"} == 1) / count(up{job=\"apiserver\",cluster=~\"$Cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Controllers Up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controllers\",cluster=~\"$Cluster\"} == 1) / count(up{job=\"kube-controllers\",cluster=~\"$Cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\",cluster=~\"$Cluster\"}) / sum(kube_node_labels{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "API Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"2..\",cluster=~\"$Cluster\"}[5m])) / sum(rate(apiserver_request_count{cluster=~\"$Cluster\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(    node:node_cpu_utilisation:avg1m{cluster=~\"$Cluster\"}     * on (node) group_left kube_node_status_capacity_cpu_cores{cluster=~\"$Cluster\"}       )    /     sum(          kube_node_status_capacity_cpu_cores{cluster=~\"$Cluster\"}          )"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(        (node_memory_MemTotal_bytes{cluster=~\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=~\"$Cluster\"})        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=~\"$Cluster\"}      )  / sum( kube_node_status_capacity_memory_bytes{cluster=~\"$Cluster\"} )"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",cluster=~\"$Cluster\"}) - sum(node_filesystem_free{device!=\"rootfs\",cluster=~\"$Cluster\"})) / sum(node_filesystem_size{device!=\"rootfs\",cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods{cluster=~\"$Cluster\"}) - sum(kube_pod_info{cluster=~\"$Cluster\"})) / sum(kube_node_status_capacity_pods{cluster=~\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Pod Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1 - (sum (kube_pod_status_phase{phase=\"Failed\",phase!=\"Unknown\",cluster=~\"$Cluster\"}) / sum(kube_pod_status_phase{cluster=~\"$Cluster\"})) ) * 100"
    }
   ]
  },
  {
   "title": "Crashlooping",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(kube_pod_status_phase{phase=\"Running\",cluster=~\"$Cluster\"} ) \r - sum(kube_pod_status_ready{condition=\"true\",cluster=~\"$Cluster\"}))"
    }
   ]
  }
 ]
}