{
 "title": "Pods in Namespace",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "Namespace",
    "label": "Project",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$Namespace\"}, pod) "
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pod Phase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (    \n    ( kube_pod_status_phase{namespace=\"$Namespace\",pod=~\"$Pod\"}\n      or\n      label_replace ( kube_pod_status_ready{namespace=\"$Namespace\",pod=~\"$Pod\",condition=\"true\"}, \"phase\",\"Ready\",\"\",\"\" )\n    )\n) ",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum (increase(kube_pod_container_status_restarts_total{namespace=~\"$Namespace\",pod=~\"$Pod\"} [1h] )) by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Quota (Pods)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) \n/ sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) \n/ sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)"
    }
   ]
  },
  {
   "title": "CPU Quota (Containers)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n    label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\",container_name!=\"POD\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")\n    ,  \"container\", \"$1\", \"container_name\", \"(.*)\")\n ) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(label_replace(\n    label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\",container_name!=\"POD\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")\n    ,\"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (pod,container) \n/ sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(label_replace(\n    label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$Namespace\",pod_name=~\"$Pod\",container_name!=\"POD\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")\n    ,\"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (pod,container) \n/ sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$Namespace\", container_name!=\"\",pod_name=~\"$Pod\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Quota (Pods)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$Namespace\",container_name!=\"\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$Namespace\",container_name!=\"\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) \n/ sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)  "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$Namespace\",container_name!=\"\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) \n/ sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod)  "
    }
   ]
  },
  {
   "title": "Memory Quota (Containers)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n    label_replace(container_memory_usage_bytes{namespace=\"$Namespace\",container_name!=\"\",pod_name=~\"$Pod\",container_name!=\"POD\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")\n    ,\"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (pod,container)  "
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(label_replace(\n    label_replace(container_memory_usage_bytes{namespace=\"$Namespace\",container_name!~\"POD|\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")\n    ,\"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (pod,container) \n/ sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    },
    {
     "expr": "sum(label_replace(\n    label_replace(container_memory_usage_bytes{namespace=\"$Namespace\",container_name!~\"POD|\",pod_name=~\"$Pod\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")\n    ,\"container\", \"$1\", \"container_name\", \"(.*)\")\n    ) by (pod,container) \n/ sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$Namespace\",pod=~\"$Pod\"}) by (pod,container)"
    }
   ]
  }
 ]
}