{
 "title": "Summary by node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_labels{},node)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Totals for selected nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Selected nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (node,nodetype) (\nlabel_replace(\nlabel_replace(\nlabel_replace(kube_node_labels{node=~\"$node\"}\n    ,\"nodetype\",\"master\",\"label_node_role_kubernetes_io_master\",\"true\")\n    ,\"nodetype\",\"infra\",\"label_node_role_kubernetes_io_infra\",\"true\")\n    ,\"nodetype\",\"compute\",\"label_node_role_kubernetes_io_compute\",\"true\")\n)"
    }
   ]
  },
  {
   "title": "Node issues",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max by (node,condition)(\n    kube_node_status_condition{status=\"true\",condition!=\"Ready\",node=~\"$node\"} > 0\n    ) "
    }
   ]
  },
  {
   "title": "Pod phase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (    \n    (\n        kube_pod_status_phase{}\n        or\n        label_replace ( kube_pod_status_ready{condition=\"true\"}, \"phase\",\"Ready\",\"\",\"\" )\n    )\n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "CPU node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    node:node_cpu_utilisation:avg1m{} \n    * on (node) group_left kube_node_status_capacity_cpu_cores{node=~\"$node\"}   \n    )    \n/     \nsum(      \n    kube_node_status_capacity_cpu_cores{node=~\"$node\"}      \n    )"
    }
   ]
  },
  {
   "title": "CPU usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n    )\n/ \nsum (\n    kube_node_status_allocatable_cpu_cores{node=~\"$node\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU usage/requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n    )\n/ \nsum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU  requests/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}       \n    )\n/\nsum(    \n    kube_node_status_allocatable_cpu_cores{node=~\"$node\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{node=~\"$node\"}       \n)\n/\nsum(    \n    kube_node_status_allocatable_cpu_cores{node=~\"$node\"}       \n)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}   \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}   \n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(       \n    node:node_cpu_utilisation:avg1m{} * on (node) group_left() \n    (kube_node_status_capacity_cpu_cores{} * on (node) group_left kube_node_labels{node=~\"$node\"})    \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}     \n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{node=~\"$node\"}       \n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n    )  \n/ \nsum( kube_node_status_capacity_memory_bytes{node=~\"$node\"} )"
    }
   ]
  },
  {
   "title": "Memory usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n    )  \n/ \nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory usage/requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n    )  \n/ \nsum(\n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}\n)"
    }
   ]
  },
  {
   "title": "Memory requests/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}       \n)\n/\nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\"})\n"
    }
   ]
  },
  {
   "title": "Memory limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_memory_bytes{node=~\"$node\"}       \n)\n/\nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\"})\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum( kube_node_status_capacity_memory_bytes{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}  \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum( kube_node_status_allocatable_memory_bytes{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}  \n)\n",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}       \n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_memory_bytes{node=~\"$node\"}       \n)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node:node_net_utilisation:sum_irate{node=~\"$node\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (\n    irate(node_network_receive_bytes{job=\"node-exporter\",device!~\"veth.+\"}[1m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (\n    irate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"veth.+\"}[1m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n)",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( \n  irate(node_disk_bytes_read[5m]) \n  * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum( \n  irate(node_disk_bytes_written[5m]) \n  * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(   \n    node:node_disk_utilisation:avg_irate{node=~\"$node\"}\n)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Filesystem %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (device,pod,namespace)(\n    node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"} - node_filesystem_avail{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"}\n)\n/ \nmax by (device,pod,namespace)(\n    node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"}\n)\n* on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}",
     "legendFormat": "{{node}} - {{device}}"
    }
   ]
  },
  { "title": "Node - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "node" },
  {
   "title": "Node",
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "content": "<h1 align=\"center\">$node</h1>"
  },
  {
   "title": "Node issues",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "max by (node,condition)(\n    kube_node_status_condition{status=\"true\",condition!=\"Ready\",node=~\"$node\"} > 0\n    ) "
    }
   ]
  },
  {
   "title": "Pod phase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (    \n    (\n        kube_pod_status_phase{}\n        or\n        label_replace ( kube_pod_status_ready{condition=\"true\"}, \"phase\",\"Ready\",\"\",\"\" )\n    )\n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "CPU node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    node:node_cpu_utilisation:avg1m{} \n    * on (node) group_left kube_node_status_capacity_cpu_cores{node=~\"$node\"}   \n    )    \n/     \nsum(      \n    kube_node_status_capacity_cpu_cores{node=~\"$node\"}      \n    )"
    }
   ]
  },
  {
   "title": "CPU usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n    )\n/ \nsum (\n    kube_node_status_allocatable_cpu_cores{node=~\"$node\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU usage/requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n    )\n/ \nsum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU  requests/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}       \n    )\n/\nsum(    \n    kube_node_status_allocatable_cpu_cores{node=~\"$node\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 29 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{node=~\"$node\"}       \n)\n/\nsum(    \n    kube_node_status_allocatable_cpu_cores{node=~\"$node\"}       \n)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}   \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}   \n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(       \n    node:node_cpu_utilisation:avg1m{} * on (node) group_left() \n    (kube_node_status_capacity_cpu_cores{} * on (node) group_left kube_node_labels{node=~\"$node\"})    \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"}     \n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{node=~\"$node\"}       \n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n    )  \n/ \nsum( kube_node_status_capacity_memory_bytes{node=~\"$node\"} )"
    }
   ]
  },
  {
   "title": "Memory usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n    )  \n/ \nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory usage/requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n    )  \n/ \nsum(\n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}\n)"
    }
   ]
  },
  {
   "title": "Memory requests/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}       \n)\n/\nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\"})\n"
    }
   ]
  },
  {
   "title": "Memory limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 35 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_memory_bytes{node=~\"$node\"}       \n)\n/\nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\"})\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum( kube_node_status_capacity_memory_bytes{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}  \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum( kube_node_status_allocatable_memory_bytes{}   \n    * on (node) group_left kube_node_labels{node=~\"$node\"}  \n)\n",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\"}       \n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_memory_bytes{node=~\"$node\"}       \n)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node:node_net_utilisation:sum_irate{node=~\"$node\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n    irate(node_network_receive_bytes{job=\"node-exporter\",device!~\"veth.+\"}[5m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(\n    irate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"veth.+\"}[5m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}\n)",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum( \n  irate(node_disk_bytes_read[5m]) \n  * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum( \n  irate(node_disk_bytes_written[5m]) \n  * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}  \n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(   \n    node:node_disk_utilisation:avg_irate{node=~\"$node\"}\n)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Filesystem %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (device,pod,namespace)(\n    node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"} - node_filesystem_avail{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"}\n)\n/ \nmax by (device,pod,namespace)(\n    node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"}\n)\n* on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}",
     "legendFormat": "{{node}} - {{device}}"
    }
   ]
  }
 ]
}