{
 "title": "Summary by node type",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "nodetype", "label": "Node type", "query": "master,infra,compute" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (node,nodetype) (\nlabel_replace(\nlabel_replace(\nlabel_replace(kube_node_labels{}\n    ,\"nodetype\",\"master\",\"label_node_role_kubernetes_io_master\",\"true\")\n    ,\"nodetype\",\"infra\",\"label_node_role_kubernetes_io_infra\",\"true\")\n    ,\"nodetype\",\"compute\",\"label_node_role_kubernetes_io_compute\",\"true\")\n)"
    }
   ]
  },
  {
   "title": "Node health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(max(kube_node_status_condition{status=\"true\",condition!=\"Ready\"} > 0) by (node))"
    }
   ]
  },
  {
   "title": "Node issues",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(kube_node_status_condition{status=\"true\",condition!=\"Ready\"} > 0) by (node,condition)"
    }
   ]
  },
  { "title": "Summary - $nodetype", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "nodetype" },
  {
   "title": "CPU node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(       \n    node:node_cpu_utilisation:avg1m{} * on (node)       \n    (kube_node_status_capacity_cpu_cores{} * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"})    \n)    \n/     \nsum(      \n    kube_node_status_capacity_cpu_cores{} * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}      \n)"
    }
   ]
  },
  {
   "title": "CPU usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )   \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n)  \n/ \nsum (    \n    kube_node_status_allocatable_cpu_cores{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"})"
    }
   ]
  },
  {
   "title": "CPU usage/requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )   \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n)\n/\nsum(    \n    kube_pod_container_resource_requests_cpu_cores{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)"
    }
   ]
  },
  {
   "title": "CPU requests/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)\n/ \nsum (    \n    kube_node_status_allocatable_cpu_cores{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)\n/ \nsum (    \n    kube_node_status_allocatable_cpu_cores{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\nkube_node_status_capacity_cpu_cores{}\n* on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\nkube_node_status_allocatable_cpu_cores{}\n* on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum( \n    node:node_cpu_utilisation:avg1m{} \n    * on (node) (\n        kube_node_status_capacity_cpu_cores{} \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n        )\n) ",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (\nlabel_replace(  \n    rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\"}[5m]),  \n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n)\n* on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}\n* on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)",
     "legendFormat": "Limits"
    },
    {}
   ]
  },
  {
   "title": "Memory node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(     \n    (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n)  \n/   \nsum(    \n    node:node_memory_bytes_total:sum{} * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}    \n)"
    }
   ]
  },
  {
   "title": "Memory allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},      \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n    )  \n/ \nsum (    \n    kube_node_status_allocatable_memory_bytes{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"})"
    }
   ]
  },
  {
   "title": "Memory usage/requests %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},      \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n    )  \n/\nsum(    \n    kube_pod_container_resource_requests_memory_bytes{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}       \n)"
    }
   ]
  },
  {
   "title": "Memory requests/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}       \n    )\n/\nsum (    \n    kube_node_status_allocatable_memory_bytes{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n    )"
    }
   ]
  },
  {
   "title": "Memory limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_memory_bytes{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}       \n    )\n/\nsum (    \n    kube_node_status_allocatable_memory_bytes{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n    )"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_node_status_capacity_memory_bytes{}   \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n    kube_node_status_allocatable_memory_bytes{}   \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}   \n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(     \n    (node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\"},      \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n    )    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}       \n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(       \n    kube_pod_container_resource_limits_memory_bytes{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}      \n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network (Total)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n    node:node_net_utilisation:sum_irate{}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network (Receive)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n    irate(node_network_receive_bytes{job=\"node-exporter\",device!~\"veth.+\"}[5m])\n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network (Transmit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n    irate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"veth.+\"}[5m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left  kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk bytes read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ( \n    irate(node_disk_bytes_read[5m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left  kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}  \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk bytes write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ( \n    irate(node_disk_bytes_written[5m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}    \n    * on (node) group_left  kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{}\n* on (node) group_left  kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"} \n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n  node_namespace_pod:kube_pod_info:{}\n  * on (namespace, pod) group_left kube_pod_status_ready{condition=\"true\"}\n  * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pods phase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (phase) (    \n    ( kube_pod_status_phase{}\n      or\n      label_replace ( kube_pod_status_ready{condition=\"true\"}, \"phase\",\"Ready\",\"\",\"\" )\n    )\n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{} \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"}\n) ",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Filesystem %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (device,pod,namespace)(\n    node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"} - node_filesystem_avail{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"}\n)\n/ \nmax by (device,pod,namespace)(\n    node_filesystem_size{fstype=~\"ext[234]|btrfs|xfs|zfs|nfs.*\"}\n)\n* on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{}\n* on (node) group_left  kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\"} ",
     "legendFormat": "{{node}} - {{device}}"
    }
   ]
  }
 ]
}