{
 "title": "Summary by node type",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nodetype", "label": "Node type", "query": "master,infra,compute" },
   {
    "name": "Cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary - $nodetype", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nodetype" },
  {
   "title": "CPU node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(       \n    node:node_cpu_utilisation:avg1m{cluster=\"$Cluster\"} * on (node)       \n    (kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"} * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"})    \n)    \n/     \nsum(      \n    kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"} * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}      \n)"
    }
   ]
  },
  {
   "title": "CPU usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )   \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n)  \n/ \nsum (    \n    kube_node_status_allocatable_cpu_cores{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "CPU usage/request %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )   \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n)\n/\nsum(    \n    kube_pod_container_resource_requests_cpu_cores{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)"
    }
   ]
  },
  {
   "title": "CPU request/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)\n/ \nsum (    \n    kube_node_status_allocatable_cpu_cores{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)\n/ \nsum (    \n    kube_node_status_allocatable_cpu_cores{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\nkube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"}\n* on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\nkube_node_status_allocatable_cpu_cores{cluster=\"$Cluster\"}\n* on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum( \n    node:node_cpu_utilisation:avg1m{cluster=\"$Cluster\"} \n    * on (node) (\n        kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"} \n        * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n        )\n) ",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (\nlabel_replace(  \n    rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),  \n    \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n)\n* on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}\n* on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_cpu_cores{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Limits"
    },
    {}
   ]
  },
  {
   "title": "Memory node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(     \n    (node_memory_MemTotal_bytes{cluster=\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$Cluster\"})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n)  \n/   \nsum(    \n    node:node_memory_bytes_total:sum{cluster=\"$Cluster\"} * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}    \n)"
    }
   ]
  },
  {
   "title": "Memory allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},      \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum (    \n    kube_node_status_allocatable_memory_bytes{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Memory usage/request %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},      \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n        * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n    )  \n/\nsum(    \n    kube_pod_container_resource_requests_memory_bytes{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}       \n)"
    }
   ]
  },
  {
   "title": "Memory request/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}       \n    )\n/\nsum (    \n    kube_node_status_allocatable_memory_bytes{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n    )"
    }
   ]
  },
  {
   "title": "Memory limits/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_limits_memory_bytes{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}       \n    )\n/\nsum (    \n    kube_node_status_allocatable_memory_bytes{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}\n    )"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    kube_node_status_capacity_memory_bytes{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n    kube_node_status_allocatable_memory_bytes{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(     \n    (node_memory_MemTotal_bytes{cluster=\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$Cluster\"})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},      \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n    )    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}       \n)",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(       \n    kube_pod_container_resource_limits_memory_bytes{cluster=\"$Cluster\"}\n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"}      \n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network (Total)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n    node:node_net_utilisation:sum_irate{cluster=\"$Cluster\"}\n    * on (node) kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network (Receive)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n    irate(node_network_receive_bytes{job=\"node-exporter\",device!~\"veth.+\",cluster=\"$Cluster\"}[5m])\n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n    * on (node) group_left kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network (Transmit)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n    irate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"veth.+\",cluster=\"$Cluster\"}[5m]) \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{cluster=\"$Cluster\"}    \n    * on (node) group_left  kube_node_labels{label_node_role_kubernetes_io_$nodetype=\"true\",cluster=\"$Cluster\"} \n)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}