{
 "title": "Summary by node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_labels{cluster=\"$Cluster\"},node)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Selected nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    node:node_cpu_utilisation:avg1m{cluster=\"$Cluster\"} \n    * on (node) kube_node_status_capacity_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}   \n    )    \n/     \nsum(      \n    kube_node_status_capacity_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}      \n    )"
    }
   ]
  },
  {
   "title": "CPU usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}\n    )\n/ \nsum (\n    kube_node_status_allocatable_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU usage/request %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}\n    )\n/ \nsum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU  request/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}       \n    )\n/\nsum(    \n    kube_node_status_allocatable_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(       \n    node:node_cpu_utilisation:avg1m{cluster=\"$Cluster\"} * on (node)       \n    (kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"} * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"})    \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}     \n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{cluster=\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$Cluster\"})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum( kube_node_status_capacity_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"} )"
    }
   ]
  },
  {
   "title": "Memory usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Memory usage/request %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum(\n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"}\n)"
    }
   ]
  },
  {
   "title": "Memory request/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"}       \n)\n/\nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"})\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum( kube_node_status_capacity_memory_bytes{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum( kube_node_status_allocatable_memory_bytes{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}  \n)\n",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{cluster=\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$Cluster\"})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"}       \n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node:node_net_utilisation:sum_irate{node=~\"$node\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (\n    irate(node_network_receive_bytes{job=\"node-exporter\",device!~\"veth.+\",cluster=\"$Cluster\"}[1m]) \n    * on (namespace, pod) group_left(node) kube_pod_info{node=~\"$node\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (\n    irate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"veth.+\",cluster=\"$Cluster\"}[1m]) \n    * on (namespace, pod) group_left(node) kube_pod_info{node=~\"$node\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Send"
    }
   ]
  },
  { "title": "Node - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "node" },
  {
   "title": "CPU node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n    node:node_cpu_utilisation:avg1m{cluster=\"$Cluster\"} \n    * on (node) kube_node_status_capacity_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}   \n    )    \n/     \nsum(      \n    kube_node_status_capacity_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}      \n    )"
    }
   ]
  },
  {
   "title": "CPU usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}\n    )\n/ \nsum (\n    kube_node_status_allocatable_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}\n    )"
    }
   ]
  },
  {
   "title": "CPU usage/request %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),\n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"\n        )\n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}\n    )\n/ \nsum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU  request/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}       \n    )\n/\nsum(    \n    kube_node_status_allocatable_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}       \n    )"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}   \n)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(       \n    node:node_cpu_utilisation:avg1m{cluster=\"$Cluster\"} * on (node)       \n    (kube_node_status_capacity_cpu_cores{cluster=\"$Cluster\"} * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"})    \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum (    \n    label_replace(      \n        rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\",cluster=\"$Cluster\"}[5m]),        \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_cpu_cores{node=~\"$node\",cluster=\"$Cluster\"}     \n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Memory node %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{cluster=\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$Cluster\"})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum( kube_node_status_capacity_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"} )"
    }
   ]
  },
  {
   "title": "Memory usage/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Memory usage/request %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    )    \n        * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n    )  \n/ \nsum(\n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"}\n)"
    }
   ]
  },
  {
   "title": "Memory request/allocatable %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"}       \n)\n/\nsum (kube_node_status_allocatable_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"})\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum( kube_node_status_capacity_memory_bytes{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum( kube_node_status_allocatable_memory_bytes{cluster=\"$Cluster\"}   \n    * on (node) kube_node_labels{node=~\"$node\",cluster=\"$Cluster\"}  \n)\n",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(    \n    (node_memory_MemTotal_bytes{cluster=\"$Cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$Cluster\"})    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Node usage"
    },
    {
     "expr": "sum(    \n    label_replace(      \n        container_memory_usage_bytes{pod_name!=\"\",container_name=\"\",cluster=\"$Cluster\"},       \n        \"pod\", \"$1\", \"pod_name\", \"(.*)\"    \n        )    \n    * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:{node=~\"$node\",cluster=\"$Cluster\"}  \n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(    \n    kube_pod_container_resource_requests_memory_bytes{node=~\"$node\",cluster=\"$Cluster\"}       \n)\n",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node:node_net_utilisation:sum_irate{node=~\"$node\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n    irate(node_network_receive_bytes{job=\"node-exporter\",device!~\"veth.+\",cluster=\"$Cluster\"}[1m]) \n    * on (namespace, pod) group_left(node) kube_pod_info{node=~\"$node\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(\n    irate(node_network_transmit_bytes{job=\"node-exporter\",device!~\"veth.+\",cluster=\"$Cluster\"}[1m]) \n    * on (namespace, pod) group_left(node) kube_pod_info{node=~\"$node\",cluster=\"$Cluster\"}\n)",
     "legendFormat": "Send"
    }
   ]
  }
 ]
}